config/routes.rb
Rails.application.routes.draw do


  get 'homes/top'
  root to: 'public/homes#top'
  devise_scope :customer do
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'

    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
  end

  devise_for :customers, skip: [:registrations, :sessions, :passwords]


  devise_for :admins, controllers: {
    sessions:      'admins/sessions'
  }

  scope module: :public do
    # scope module: :●● doで「●●/index」を「/index」みたいな感じに変更できる

    get 'about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]



    # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end



    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end


  end

  namespace :admin do
    root to: 'homes#top'
    # resourceだけだとidが含まれないかつindexアクションも表示されないから気をつける
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end



end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre

  attachment :image

  has_many :cart_items
  has_many :order_details



 enum is_active: { on_sale: 0, off_sale: 1 }


  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  
# 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
 before_action :authenticate_admin!
 
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_items_path
      # もし保存されなかったらitem/newへ
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


 private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">商品編集</h3>
    </div>
    <%= form_with model: @item, url: admin_item_path(@item), local: true do |f| %>
    <div class="form-group has-icon">
      <tr>
        <th>商品画像</th>
        <td><%= f.attachment_field :image %></td>
        </tr>
      </div>

      <div class="form-group has-icon">
        <tr>
          <th>商品名</th>
          <td><%= f.text_field :name, class:"form-control" %></td>
        </tr>
      </div>

      <div class="form-group has-icon">
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area :introduction, class:"form-control" %></td>
        </tr>
       </div>

      <div class="form-group has-icon">
        <tr>
        　<th>ジャンル</th>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--", class:"form-control" %></td>
        </tr>
      </div>

      <div class="form-group has-icon">
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field :price, class:"form-control" %></td>
        </tr>
      </div>

          <!--<div class="form-group has-icon">-->
          <!--  <tr>-->
          <!--    <th>販売ステータス</th>-->
          <!--    <td>-->

          <!--    </td>-->
          <!--　</tr>-->
          <!--</div>-->

      <div class="form-group">
        <tr>
          <th></th>
          <td>
          <%= f.submit "変更を保存", class:"btn btn-outline-success" %>
          </td>
        </tr>
      </div>
      <% end %>

    </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">商品一覧</h3>
    </div>

      <div class="text-right">
       <%= link_to "＋", new_admin_item_path, class: "btn btn-outline-secondary" %>
      </div>

      <table class="table table-striped bg-light">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <!--<th>ステータス</th>-->
      </tr>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <!--<td><%= item.is_active %></td>-->
        </tr>
      <% end %>

    </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">商品新規登録</h3>
    </div>
      
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
          
          <div class="form-group has-icon">
            <tr>
              <th>商品画像</th>
              <td><%= f.attachment_field :image %></td>
            </tr>
          </div>
          
          <div class="form-group has-icon">
            <tr>
              <th>商品名</th>
              <td><%= f.text_field :name, class:"form-control" %></td>
            </tr>
          </div>
          
          <div class="form-group has-icon">
            <tr>
              <th>商品説明</th>
              <td><%= f.text_area :introduction, class:"form-control" %></td>
            </tr>
          </div>
          
          <div class="form-group has-icon">
            <tr>
            <th>ジャンル</th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></td>
            </tr>
          </div>
          
          <div class="form-group has-icon">
            <tr>
              <th>税抜価格</th>
              <td><%= f.text_field :price, class:"form-control" %></td>
            </tr>
          </div>
          
          <!--<div class="form-group has-icon">-->
          <!--  <tr>-->
          <!--    <th>販売ステータス</th>-->
          <!--    <td>-->
        
          <!--    </td>-->
          <!--　</tr>-->
          <!--</div>-->
          
          <div class="form-group">
            <tr>
              <th></th>
              <td>
                <%= f.submit "新規登録", class:"btn btn-outline-success" %>
              </td>
            </tr>
          </div>
          
        <% end %>
  
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">商品詳細</h3>
    </div>
    <div class="row">
      <div class="col-6">
        <%= attachment_image_tag @item, :image,format: 'jpeg', style: "max-width: 70%" %>
      </div>
      <div class="col-md-10 col-md-offset-1">
        <table class="table table-borderless">
          <tr>
            <th>商品名</th>
            <td class="font-weight-bold"><%= @item.name %></td>
          </tr>
          <tr>
            <th>商品説明</th>
            <td class="font-weight-bold"><%= @item.introduction %></td>
          </tr>

          <tr>
            <th>ジャンル</th>
            <td class="font-weight-bold"><%= @item.genre.name %></td>
          </tr>

          <tr>
            <!--切り捨て(price * tax).floor-->
            <th>税抜き価格 <br>税込価格</th>
            <td class="font-weight-bold"><%= @item.price %>円<br>
            <%= (@item.price* 1.1).floor %>円</td>
          </tr>

          <!--<tr>-->
          <!--  <th>販売ステータス</th>-->
          <!--</tr>-->
          <th></th>
          <td>
            <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-outline-success" %>
          </td>

        </table>
      </div>
    </div>


    </div>
</div>