config/routes.rb
Rails.application.routes.draw do


  get 'homes/top'
  root to: 'public/homes#top'
  devise_scope :customer do
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'

    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
  end

  devise_for :customers, skip: [:registrations, :sessions, :passwords]


  devise_for :admins, controllers: {
    sessions:      'admins/sessions'
  }

  scope module: :public do
    # scope module: :●● doで「●●/index」を「/index」みたいな感じに変更できる

    get 'about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]



    # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end



    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end


  end

  namespace :admin do
    root to: 'homes#top'
    # resourceだけだとidが含まれないかつindexアクションも表示されないから気をつける
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy



        # 必須項目
         validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

        #退会ユーザーはログインできなくする
        # ログインする時に退会済み(is_active==true)のユーザーを弾くためのメソッド
        
        # 
        # def active_for_authentication?
        #     super && (self.is_active == false)
        # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

 before_action :authenticate_admin!

# 管理者ページの顧客のコントローラ

  def index
    @customers = Customer.all
  end

  def show
    # 顧客の詳細
    @customer = Customer.find(params[:id])
  end

  def edit
    # 顧客の会員情報編集
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
  	if @customer.update(customer_params)
  		redirect_to admin_customer_path(@customer)
  	else
  		render "edit"
  	end
  end



  private

  def customer_params
  	params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :postal_code,:address, :phone_number, :is_active)
  end


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end


  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
     if (@customer.valid_password?(params[:customer][:password]) && !@customer.is_active)
      flash[:error] = "退会済みです。新たにアカウントを作成してください。"
      redirect_to customers_sign_up_path
     else
      flash[:error] = "必須項目を入力してください。"
     end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h3>
  </div>

  <%= form_with model:@customer, url: admin_customer_path(@customer), local:true do |f| %>
  <div class="form-group row">
    <%= f.label :id,"会員ID" , class:"col-sm-2 col-form-label" %>
    <%= f.text_field :id, class:"form-control col-sm-3" %>
  </div>
   <div class="form-group row">
    <%= f.label :name,"氏名" , class:"col-sm-2 col-form-label" %>
    <%= f.text_field :first_name, class:"form-control col-sm-3 ml-3" %>
    <%= f.text_field :last_name, class:"form-control col-sm-3" %>
  </div>
  <div class="form-group row">
    <%= f.label :name,"フリガナ" , class:"col-sm-2 col-form-label" %>
    <%= f.text_field :first_name_kana, class:"form-control col-sm-3 ml-3" %>
    <%= f.text_field :last_name_kana, class:"form-control col-sm-3" %>
  </div>
  <div class="form-group row">
    <%= f.label :postal_code,"郵便番号" , class:"col-sm-2 col-form-label" %>
    <%= f.text_field :postal_code, class:"form-control col-sm-3" %>
  </div>
  <div class="form-group row">
    <%= f.label :address, "住所", class: "col-sm-2 col-form-label" %>
    <%= f.text_field :address, class: "form-control col-sm-6" %>
  </div>
  <div class="form-group row">
    <%= f.label :telephone_number, "電話番号", class: "col-sm-2 col-form-label" %>
    <%= f.text_field :telephone_number, class: "form-control col-sm-3" %>
  </div>
  <div class="form-group row">
    <%= f.label  "メールアドレス", class: "col-sm-2 col-form-label" %>
    <%= f.text_field :email, class: "form-control col-sm-3" %>
  </div>
  <div class="form-group row">
    <%= f.label "有効ステータス", class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.label :is_active, '有効' %>
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active, '退会' %>
      <%= f.radio_button :is_active, :false %>
    </div>
  </div>
  <div><%= f.submit "変更を保存する", class:"btn btn-primary" %></div>

  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">会員一覧</h3>
    </div>
    <div class="row">
       <table class="table table-hover table-inverse">
          <thead>
            <tr class="table-secondary">
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>会員ステータス</th>
            </tr>
          </thead>
           <tbody>
             <% @customers.each do |customer| %>
             <tr>
               <td><%= customer.id %></td>
               <td><%= link_to customer.first_name + customer.last_name, admin_customer_path(customer) %></td>
      　　    　  <td><%= customer.email %></td>
      　　    　 <td>
      　　    　   <% if customer.is_active %>
                <span class="green">有効</span>
                <% else %>
                <span class="secondary">退会</span>
                <% end %>
              </td>

      　　　  　</tr>
      　　　<% end %>
        </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細ページ</h3>
    </div>
    <div class="row">
      <table class="table">

      <tr>
       <th class="col-xs-2">会員ID</th>
       <td class="col-xs-10"><%= @customer.id %></td>
      </tr>

      <tr>
       <th class="col-xs-2">氏名</th>
       <td class="col-xs-10"><%= @customer.first_name %> <%= @customer.last_name %></td>
      </tr>

      <tr>
       <th class="col-xs-2">フリガナ</th>
       <td class="col-xs-10"><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
      </tr>

      <tr>
       <th class="col-xs-2">郵便番号</th>
       <td class="col-xs-10"><%= @customer.postal_code %></td>
      </tr>

      <tr>
       <th class="col-xs-2">住所</th>
       <td class="col-xs-10"><%= @customer.address %></td>
      </tr>

      <tr>
       <th class="col-xs-2">電話番号</th>
       <td class="col-xs-10"><%= @customer.telephone_number %></td>
      </tr>

      <tr>
       <th class="col-xs-2">メールアドレス</th>
       <td class="col-xs-10"><%= @customer.email %></td>
      </tr>

      <tr>
       <th class="col-xs-2">会員ステータス</th>
       <td class="col-xs-10">
        <% if @customer.is_active %>
        <span class="green">有効</span>
        <% else %>
        <span class="secondary">退会</span>
        <% end %>
        </td>
      </tr>

     </table>
    <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-outline-success" %>
    <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary ml-3" %>
    </div>
  </div>
</div>