config/routes.rb
Rails.application.routes.draw do


  get 'homes/top'
  root to: 'public/homes#top'
  devise_scope :customer do
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'

    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
  end

  devise_for :customers, skip: [:registrations, :sessions, :passwords]


  devise_for :admins, controllers: {
    sessions:      'admins/sessions'
  }

  scope module: :public do
    # scope module: :●● doで「●●/index」を「/index」みたいな感じに変更できる

    get 'about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]



    # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end



    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end


  end

  namespace :admin do
    root to: 'homes#top'
    # resourceだけだとidが含まれないかつindexアクションも表示されないから気をつける
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end



end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    # index.htmlのなかに投稿機能
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:error] = "ジャンル名を入力してください"
      render :index

    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
      redirect_to admin_genres_path
  end

  private
   def genre_params
     params.require(:genre).permit(:name)
   end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">ジャンル編集</h3>
    </div>
    
    <div class="row">
    <%= form_with model: @genre, url: admin_genre_path(@genre), local: true do |f| %>
    <p class="d-inline-block">ジャンル名</p>
    <%= f.text_field :name %>
    <%= f.submit '変更を保存', class: "btn btn-outline-success" %>
    <% end %>
    </div>
    
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="error"><%= flash[:error] %></div>
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="d-flex aligin-items-center">
      <h3 class="p-3 md-10 bg-secondary text-white">ジャンル一覧・追加</h3>
    </div>
 <div class="row">
  <div class="col-md-11 offset-md-1">
    <div class="row">
      <%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
        <p class="d-inline-block">ジャンル名</p>
        <%= f.text_field :name, class: "ml-3" %>
        <%= f.submit'新規登録', class: "btn btn-outline-success" %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th></th>
              <th>ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to '編集する', edit_admin_genre_path(genre), class: "btn btn-outline-success" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
</div>