config/routes.rb
Rails.application.routes.draw do


  get 'homes/top'
  root to: 'public/homes#top'
  devise_scope :customer do
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'

    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
  end

  devise_for :customers, skip: [:registrations, :sessions, :passwords]


  devise_for :admins, controllers: {
    sessions:      'admins/sessions'
  }

  scope module: :public do
    # scope module: :●● doで「●●/index」を「/index」みたいな感じに変更できる

    get 'about' => 'homes#about'
    resources :items, only: [:index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]



    # 7つ以外のアクションがある時は，collection(idなし)とmember(id含む)を使って指定する。
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end



    resource :customers, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end


  end

  namespace :admin do
    root to: 'homes#top'
    # resourceだけだとidが含まれないかつindexアクションも表示されないから気をつける
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end



end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true

  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end

  # 合計を求めるメソッド
  def sum_of_price
    item.with_tax_price * amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy



        # 必須項目
         validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true

        #退会ユーザーはログインできなくする
        # ログインする時に退会済み(is_active==true)のユーザーを弾くためのメソッド
        
        # 
        # def active_for_authentication?
        #     super && (self.is_active == false)
        # end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre

  attachment :image

  has_many :cart_items
  has_many :order_details



 enum is_active: { on_sale: 0, off_sale: 1 }


  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  
# 消費税を求めるメソッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy





  # validates_presence_of :name, :address,:pay_type => "を入力して下さい。"

  enum payment_method: { credit_card: 0, transfer: 1 }




  attribute :status, :integer, default: '0'

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    # index.htmlのなかに投稿機能
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:error] = "ジャンル名を入力してください"
      render :index

    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
      redirect_to admin_genres_path
  end

  private
   def genre_params
     params.require(:genre).permit(:name)
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
 before_action :authenticate_admin!
 
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to admin_items_path
      # もし保存されなかったらitem/newへ
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end


 private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    if current_customer
     root_path

    elsif Admin
     admin_root_path
    end
  end

    def after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
        root_path
      elsif resource_or_scope == :admin
        admin_session_path
      end
    end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  # def after_sign_out_path_for(resource)
  #   new_admin_session_path
  # end

  # def after_sign_up_path_for(resource)
  #   admin_items_path
  # end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-light">
       <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if customer_signed_in? %>
            <li>ようこそ、<%= current_customer.last_name %>さん！</li>

              <li class = "nav-item">
                <%= link_to "マイページ", customers_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class = "nav-item">
                <%= link_to "商品一覧", items_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class = "nav-item">
                <%= link_to "カート", cart_items_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class = "nav-item">
                <%= link_to "ログアウト", customers_sign_out_path, class: 'btn btn-light ml-3',method: :delete %>
              </li>

           <% elsif admin_signed_in? %>
              <li class = "nav-item">
                <%= link_to "商品一覧", admin_items_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class = "nav-item">
                <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class = "nav-item">
                <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-light ml-3' %>
              </li>

             <li class = "nav-item">
               <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class = "nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, class: 'btn btn-light ml-3' ,method: :delete %>
              </li>

            <% else %>

              <li class="nav-item">
               <%= link_to "About", about_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class="nav-item">
               <%= link_to "新規登録", customers_sign_up_path, class: 'btn btn-light ml-3' %>
              </li>

              <li class="nav-item">
               <%= link_to "ログイン", customers_sign_in_path, class: 'btn btn-light ml-3' %>
             </li>
            <% end %>
          </ul>
        </div>
       </div>
    </nav>
  </header>

    <main>
         <h5 class="notice"><%= notice %></h5>
         <h5 class="alert"><%= alert %></h5>
         <%= yield %>
      </div>



    </main>
    <footer>
      <div class="border-bottom border-dark ml-auto"></div>
    </footer>
  </body>
</html>